/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matches;

import matches.ai.AlwaysWinningMatchesAI;
import matches.ai.MatchesAI;
import matches.communicator.MatchesCommunicator;
import matches.communicator.StdIOMatchesCommunicator;
import matches.game.MatchesGame;

public class App {

    private final static MatchesAI AI = new AlwaysWinningMatchesAI();
    private final static MatchesCommunicator COMMUNICATOR = new StdIOMatchesCommunicator();
    private final static int START_MATCHES_COUNT = 20;
    private final static int MAX_MATCHES_TO_PICK = 3;

    public static void main(String[] args) {
        MatchesGame game = new MatchesGame(AI, COMMUNICATOR, START_MATCHES_COUNT, MAX_MATCHES_TO_PICK);
        game.run();
    }
}
